### ISSUE TITLE
Papi placeholders not updating in menus (1.21.1)

### ISSUE THREAD

**Issue by GrimPlayzs** [zetastormy/deluxe-hub#20]
### Describe the bug

I use custom placeholders using papi to display the current player count and server status (offline or online). However, these variables never change from their default value.

### Link to latest.log file

No errors apears.

### Steps to reproduce

Add a papi placeholder to a menu item.
See if the value changes.

### Expected behavior

I expected the placeholders to update accordantly.

### Technical information

Paper
1.21.1
Akroplis 1.6.0

**Comment by zetastormy** [comment]
Thank you for reporting, but they work just fine for me. Remember to set the `refresh.enabled` value to `true` in your menu configuration, like this:

```yaml
# Automatically update open inventories.
# This can be used to update placeholders in the GUI.
refresh:
  enabled: true
  rate: 40
```
